name: Render Markdown content

on:
  push:
    branches:
      - main

env:
  REPO: "${{ github.GITHUB_SERVER_URL }}/${{ github.GITHUB_REPOSITORY }}"
  HTTP: ""

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Set up minifier
        run: |
          curl --location --show-error --silent --output /usr/bin/minhtml https://github.com/wilsonzlin/minify-html/releases/download/v0.16.4/minhtml-0.16.4-x86_64-unknown-linux-gnu
          chmod +x /usr/bin/minhtml

      - name: Render Markdown content
        run: |
          make render-all HTTP=${{ HTTP }} REPO=${{ env.REPO }}
          rm --force --recursive *file .github .gitignore .html.? .json template.html
          minhtml --keep-closing-tags --minify-css **/*.html
